### ISSUE TITLE
CI pipeline/ GitHub Actions

### ISSUE THREAD

**Issue by Beleifte** [Caca-XP/Realm-of-Feasts#12]
**Describe the bug**
The CI pipeline currently failing due to testing dependencies 

**Expected behaviour**
Pipeline to work

**Comment by NadiaPrasetyo** [comment]
Pipeline is currently failing due to CodeQL tests. The original MS Build and test pipeline is working. However, the codecov report that is made is unusable due to its failure in reading the source codes. Not sure how to fix, will ask Vaughn in tomorrow's tutorial.
